### ISSUE TITLE
Can't find a device placement for the op!

### ISSUE THREAD

**Issue by Julius-ZCJ** [JerryJiaGit/facenet_trt#6]
@JerryJiaGit  Hi, I have successed install tensorrt, but when I run the model, this mistake is raise:

     Can't find a device placement for the op!
my gpu is p100
tensorflow 1.12.0
tensorrt 5.0.2.6
python 3.5

**Comment by JerryJiaGit** [comment]
Hi Julius,
Thanks for the response. 
You could check sample log from https://github.com/JerryJiaGit/facenet_trt/blob/master/log.txt
The warning may not a real issue, because some of the layers are not customized optimizing for TensorRT.

This example here is a quick convert and implement to use TensorRT optimizing with minimum changes for Facenet.

My suggestion is that you could do some run time or speed perf check with/without TensorRT.

Thanks,.
Jerry

**Comment by Julius-ZCJ** [comment]
@JerryJiaGit    Alright, so do you know some others ways to compress  and accelerate model?
    Have you any suggest?

**Comment by JerryJiaGit** [comment]
You could try plugin layers, pls check more starting from :
https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#extending

It is a better way to use TensorRT.

**Comment by JerryJiaGit** [comment]
Encourage you can share more study result with TensorRT plugin. 
For this, if there is no other request, I will close in next week.
